### PR TITLE
Clean up build

### PR DESCRIPTION
**Pull request by matejvasek**

### CODE REVIEW

**Comment by lance** [comment]
@matejvasek is this still a work in progress?

**Comment by matejvasek** [comment]
@lance I think it's good enough.

**Comment by matejvasek** [comment]
I was thinking of some more improvements but I rather leave it for latter.

There is still some redundancy I believe we could get rid off some `*.toml`s and generate them instead.

I also tired to use `Go` client instead of `pack` but it let me down a little bit: I thought I could keep all config as `Go` literals and not use `toml` completely, but how wrong I was! Some members of `XYZOptions` struct (passed to the client) cannot be populated in `Go` code because some of the types are `internal`, so `toml` is needed :disappointed: .

**Review by lance — APPROVED** [review]
lgtm - thanks for cleaning this stuff up

**Pull request merged**
