### PR TITLE
chore: remove the Node.js `runtime` folder

### PR DESCRIPTION
**Pull request by lance**
This is no longer used by Boson `func` templates.

Signed-off-by: Lance Ball <lball@redhat.com>

### CODE REVIEW

**Comment by matejvasek** [comment]
@lance  Shouldn't we also remove `install_invoker()` and it's usages?

**Comment by matejvasek** [comment]
@lance you can rebase I merged test fixes.

**Comment by matejvasek** [comment]
LGTM, tests pass

**Comment by lance** [comment]
@matejvasek I also tested `func` by hand with this builder. Landing.

**Pull request merged**
